### ISSUE TITLE
Error: "The 'None' distribution was not found and is required by mnemocards"

### ISSUE THREAD

**Issue by jyrodgers** [guiferviz/mnemocards#2] opened 2020-04-29 02:05 UTC
Was super excited to use your add-on but couldn't get it to work.

After installing it this is the error that I see.

```
➜  mnemocards git:(master) ✗ mnemocards
Traceback (most recent call last):
  File "/Users/jyrodgers/.pyenv/versions/3.7.3/bin/mnemocards", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/Users/jyrodgers/.pyenv/versions/3.7.3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3191, in <module>
    @_call_aside
  File "/Users/jyrodgers/.pyenv/versions/3.7.3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3175, in _call_aside
    f(*args, **kwargs)
  File "/Users/jyrodgers/.pyenv/versions/3.7.3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3204, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/Users/jyrodgers/.pyenv/versions/3.7.3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/Users/jyrodgers/.pyenv/versions/3.7.3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Users/jyrodgers/.pyenv/versions/3.7.3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'None' distribution was not found and is required by mnemocards
```

I'm running Python 3.7.3 and pip 20.1.

Thank you for any help that you can provide.

**Comment by guiferviz** [comment] 2020-04-29 11:28
Thanks for your interest and for the bug report!
You are installing from source, right? Are you using Windows?

**Comment by guiferviz** [comment] 2020-04-29 12:05
@jyrodgers try to use the code from the attached pull request. Does it solve your problem?

**Comment by jyrodgers** [comment] 2020-04-29 15:47
@guiferviz Thanks for the quick response. 
I am installing from source. I'm on macOS.
I pulled in the PR that your linked. I was able to get past the previous error.
I'm now seeing:
```
ModuleNotFoundError: No module named 'anki'
```

Here is the full output:

```
➜  mnemocards git:(b2) ✗ mnemocards
Traceback (most recent call last):
  File "/Users/jyrodgers/.pyenv/versions/3.7.3/bin/mnemocards", line 11, in <module>
    load_entry_point('mnemocards==0.1.3', 'console_scripts', 'mnemocards')()
  File "/Users/jyrodgers/.pyenv/versions/3.7.3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/jyrodgers/.pyenv/versions/3.7.3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/Users/jyrodgers/.pyenv/versions/3.7.3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/Users/jyrodgers/.pyenv/versions/3.7.3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/jyrodgers/.pyenv/versions/3.7.3/lib/python3.7/site-packages/mnemocards-0.1.3-py3.7.egg/mnemocards/__main__.py", line 8, in <module>
    from mnemocards.clean import clean
  File "/Users/jyrodgers/.pyenv/versions/3.7.3/lib/python3.7/site-packages/mnemocards-0.1.3-py3.7.egg/mnemocards/clean.py", line 5, in <module>
    from anki import Collection
ModuleNotFoundError: No module named 'anki'
```

I did some googling and found suggestions to install 'AnkiServer'. I did this but had no change in result.

**Comment by guiferviz** [comment] 2020-04-29 16:02
Hmmm that's 100% my fault. In Linux the Anki library is installed in `/usr/share/anki` and I hardcored the path here:
https://github.com/guiferviz/mnemocards/blob/3ee6380234888b507cf8dbb5fe96badbc4e9b36b/mnemocards/import_command.py#L5

The Anki library is only needed if you want to import automatically your collection to Anki. As a temporal solution you can change that path for yours or remove all the imports of that file and not to use the `mnemocards import` command.
From this I extract two new task that I need to add to my list:
* Anki is a non-required dependency, so I need to avoid that exception. Raise that exception only when you try to import and you do not have Anki.
* Parameterize that path in some way and try to detect automatically the installation folder based on the operative system.

As now the problem is a different one, I'm going to close this issue.

**Comment by jyrodgers** [comment] 2020-04-29 17:23
I didn't have success replacing the path.

I've tried replacing `sys.path.append("/usr/share/anki"` with `sys.path.append("/Users/jyrodgers/Library/ApplicationSupport/Anki2")`and `sys.path.append("/Users/jyrodgers/Library/ApplicationSupport/Anki2/User\ 1)`where the `collection.anki2` file is located.

I've done that in the following files:
mnemocards/clean.py
mnemocards/utils.py
mnemocards/import_command.py
import_apkg.py

I've also reinstalled after changing the path. I still get the `ModuleNotFoundError: No module named 'anki'` error.
These steps did not work.

I then commented out the path and `from anki import Collection`. 

This got past the error but revealed a new one.

```
➜  examples git:(b2) ✗ mnemocards generate -r .
Building ./japanese/cards_config.json
Creating audio file ./japanese/media/hiragana/10091493812914340822.mp3
Creating audio file ./japanese/media/hiragana/7304217433350980427.mp3
Creating audio file ./japanese/media/hiragana/3595385396154511079.mp3
Creating audio file ./japanese/media/hiragana/5000408949304965326.mp3
Creating audio file ./japanese/media/hiragana/2088116759824648408.mp3
Creating audio file ./japanese/media/katakana/13050069045466478331.mp3
Creating audio file ./japanese/media/katakana/4834734646036555229.mp3
Creating audio file ./japanese/media/katakana/4275246117432970461.mp3
Creating audio file ./japanese/media/katakana/8563378359496393897.mp3
Creating audio file ./japanese/media/katakana/10683512746176998599.mp3
Traceback (most recent call last):
  File "/Users/jyrodgers/.pyenv/versions/3.7.3/bin/mnemocards", line 11, in <module>
    load_entry_point('mnemocards==0.1.3', 'console_scripts', 'mnemocards')()
  File "/Users/jyrodgers/.pyenv/versions/3.7.3/lib/python3.7/site-packages/mnemocards-0.1.3-py3.7.egg/mnemocards/__main__.py", line 18, in main
    generate(args)
  File "/Users/jyrodgers/.pyenv/versions/3.7.3/lib/python3.7/site-packages/mnemocards-0.1.3-py3.7.egg/mnemocards/generate.py", line 112, in generate
    packages = build(args)
  File "/Users/jyrodgers/.pyenv/versions/3.7.3/lib/python3.7/site-packages/mnemocards-0.1.3-py3.7.egg/mnemocards/generate.py", line 98, in build
    packages += build_dir(d, args.config_file)
  File "/Users/jyrodgers/.pyenv/versions/3.7.3/lib/python3.7/site-packages/mnemocards-0.1.3-py3.7.egg/mnemocards/generate.py", line 86, in build_dir
    packages = build_packages(data_dir, config)
  File "/Users/jyrodgers/.pyenv/versions/3.7.3/lib/python3.7/site-packages/mnemocards-0.1.3-py3.7.egg/mnemocards/generate.py", line 74, in build_packages
    package = build_package(data_dir, p)
  File "/Users/jyrodgers/.pyenv/versions/3.7.3/lib/python3.7/site-packages/mnemocards-0.1.3-py3.7.egg/mnemocards/generate.py", line 64, in build_package
    decks, media = build_decks(data_dir, package_config)
  File "/Users/jyrodgers/.pyenv/versions/3.7.3/lib/python3.7/site-packages/mnemocards-0.1.3-py3.7.egg/mnemocards/generate.py", line 57, in build_decks
    deck, m = build_deck(data_dir, d)
  File "/Users/jyrodgers/.pyenv/versions/3.7.3/lib/python3.7/site-packages/mnemocards-0.1.3-py3.7.egg/mnemocards/generate.py", line 44, in build_deck
    conf = build_deck_conf(deck_config)
  File "/Users/jyrodgers/.pyenv/versions/3.7.3/lib/python3.7/site-packages/mnemocards-0.1.3-py3.7.egg/mnemocards/generate.py", line 32, in build_deck_conf
    conf = genanki.DeckConf(deckconf_id, deckconf_name)
AttributeError: module 'genanki' has no attribute 'DeckConf'
```

When I tried to only generate the computer science directory I get this

```
➜  examples git:(b2) ✗ mnemocards generate computer_science                                                                                                                                                                                                                                                                                                           <<<
Building computer_science/cards_config.json
Traceback (most recent call last):
  File "/Users/jyrodgers/.pyenv/versions/3.7.3/bin/mnemocards", line 11, in <module>
    load_entry_point('mnemocards==0.1.3', 'console_scripts', 'mnemocards')()
  File "/Users/jyrodgers/.pyenv/versions/3.7.3/lib/python3.7/site-packages/mnemocards-0.1.3-py3.7.egg/mnemocards/__main__.py", line 18, in main
    generate(args)
  File "/Users/jyrodgers/.pyenv/versions/3.7.3/lib/python3.7/site-packages/mnemocards-0.1.3-py3.7.egg/mnemocards/generate.py", line 112, in generate
    packages = build(args)
  File "/Users/jyrodgers/.pyenv/versions/3.7.3/lib/python3.7/site-packages/mnemocards-0.1.3-py3.7.egg/mnemocards/generate.py", line 91, in build
    packages = build_dir(args.data_dir, args.config_file)
  File "/Users/jyrodgers/.pyenv/versions/3.7.3/lib/python3.7/site-packages/mnemocards-0.1.3-py3.7.egg/mnemocards/generate.py", line 86, in build_dir
    packages = build_packages(data_dir, config)
  File "/Users/jyrodgers/.pyenv/versions/3.7.3/lib/python3.7/site-packages/mnemocards-0.1.3-py3.7.egg/mnemocards/generate.py", line 74, in build_packages
    package = build_package(data_dir, p)
  File "/Users/jyrodgers/.pyenv/versions/3.7.3/lib/python3.7/site-packages/mnemocards-0.1.3-py3.7.egg/mnemocards/generate.py", line 64, in build_package
    decks, media = build_decks(data_dir, package_config)
  File "/Users/jyrodgers/.pyenv/versions/3.7.3/lib/python3.7/site-packages/mnemocards-0.1.3-py3.7.egg/mnemocards/generate.py", line 57, in build_decks
    deck, m = build_deck(data_dir, d)
  File "/Users/jyrodgers/.pyenv/versions/3.7.3/lib/python3.7/site-packages/mnemocards-0.1.3-py3.7.egg/mnemocards/generate.py", line 48, in build_deck
    conf=conf)
TypeError: __init__() got an unexpected keyword argument 'conf'
```

**Comment by guiferviz** [comment] 2020-04-29 18:25
The path is not the collection path, is the path of the Python package that should come with your installation. If you don't know where to find it maybe you can search for the `collection.py` file in all your hard drive.
Again, if you don't want Mnemocards to import your packages this is not needed.

Btw, `import_apkg.py` is a junk file, I used it for testing and forgot to delete it :D

Regarding the last two error... Did you have Genanki previously installed? Genanki is a Python library that makes easy the process of generating packages. I'm using my own version of Genanki, I added support for deck configurations (as you can see, both errors are related to deck configurations). It seems that you have the package from the public repository, not mine. Pip does not install the package if it finds a package with the same name already installed
I made a pull request some time ago to Genanki but not answer yet, so I decided to include my GitHub fork as a dependency.

# Useful links
* [Anki repository](https://github.com/ankitects/anki). The Python package is in `pylib/anki`.
* [Your same problem](https://stackoverflow.com/questions/43836018/how-to-import-third-party-python-module-mac-os-x-anki) on StackOverflow.
* [My still open pull request](https://github.com/kerrickstaley/genanki/pull/45) in the Genanki repository.

**Comment by jyrodgers** [comment] 2020-04-29 18:36
Pefect. Installing your version of genanki worked and I was able to generate the apkg files. I really appreciate your help and I'm looking forward to using your plugin.

**Closed** 2020-04-29 18:37 UTC
Labels: bug

**Comment by guiferviz** [comment] 2020-04-29 18:53
Thank you! I will try to improve those things in the next version or at least add that information in the documentation.
Feel free to open any other issue if you have problems. Also, if you want to add some feature I'll be happy to merge your pull request :)
